# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_description',
            new_name='cat_description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='cat_name',
        ),
    ]
